CREATE DATABASE gilda IF NOT EXISTS;

use gilda;

CREATE TABLE product(
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200),
  description VARCHAR(400),
  price DECIMAL,
  sku VARCHAR,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

describe product;